name: Deploy Prod
run-name: Deploy to Prod from ${{ github.ref_name }}

on:
  push:
    branches:
      - prod

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::304765577029:role/GitHubActionsDeployRole
          aws-region: us-west-2

      - name: Setup AWS SAM
        uses: aws-actions/setup-sam@v3
        with:
          use-installer: true

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Make deploy script executable
        run: chmod +x ./deploy.sh

      - name: Deploy to Prod
        run: ./deploy.sh --env prod
